### ISSUE TITLE
Form content touching overflow scroll bar in many places

### ISSUE THREAD

**Issue by ccrowley96** [microsoft/iot-cardboard-js#318]
**Describe the bug**

![image](https://user-images.githubusercontent.com/18181049/161837611-1523fcd4-3586-4ba2-85a4-006a43c8063b.png)

There should be spacing between form contents and the scroll bar

**Comment by msnyder-msft** [comment]
@ccrowley96 is this sufficiently fixed with your border PR?

**Comment by pasanchMSFT** [comment]
This has been resolved
