### ISSUE TITLE
When editing a value in the environments combo box, the cursor jumps to the end while typing

### ISSUE THREAD

**Issue by msnyder-msft** [microsoft/iot-cardboard-js#422]
**Describe the bug**
When you try to edit a prefilled value in the environment picker combo boxes the cursor jumps to the end as you type. 

**To Reproduce**
1. Go to ScenePage
2. Open environment picker
3. Select an environment
4. Highlight the first part of the path
5. Start typing
6. See the first character get added but then the cursor jumps to the end

**Expected behavior**
Should just let me type like a normal text box

**Screenshots**
![image](https://user-images.githubusercontent.com/57726991/167939417-9369954b-c9c2-4e04-917c-22d796ffbdb6.png)

**Comment by pasanchMSFT** [comment]
We are now using react-select component for these fields. This does not occur anymore.
