### ISSUE TITLE
Camera controls shift when Builder left panel loads

### ISSUE THREAD

**Issue by pasanchMSFT** [microsoft/iot-cardboard-js#460]
**Describe the bug**
When the builder screen first loads the left side panel flexes from 0 to a width that fits its contents. When the width of the left panel changes the camera controls are shifted. 

**To Reproduce**
1. Open any scene
2. Click on View mode, then click back to Build mode.
3. Notice how the controls move from left to right on panel load.

**Expected behavior**
Camera controls should not move around on mode change.

**Screenshots**
Loading:
![28](https://user-images.githubusercontent.com/55852250/169401299-c8f10837-a79b-4003-9cb8-68ba7c9b03c8.png)

Loaded:
![31](https://user-images.githubusercontent.com/55852250/169401407-3936ca17-e4c1-44ca-9973-f502617b0a84.png)

**Browser (please complete the following information):**
Edge

**Additional context**
N/A

**Comment by msnyder-msft** [comment]
@pasanchMSFT I think this is fixed now with the latest style updates. Can you confirm?

**Comment by pasanchMSFT** [comment]
@msnyder-msft The width of the panel still changes but scrollbar is gone, not sure if that means resolved.

**Comment by pasanchMSFT** [comment]
Style updates left this in an ok state, closing because we won't make more changes.
