### ISSUE TITLE
Unable to create new scene 

### ISSUE THREAD

**Issue by kmrrakesh** [microsoft/iot-cardboard-js#586]
**Describe the bug**
In add new scene page:
I fill Name, Link 3D file, Upload file(selected local .glb)
If I click on Create button, it shows me screen(like the attached screen) with message as "You have no 3D scenes, add a new one to get started and the **Add 3D Scene** button is disabled.

**To Reproduce**
1. Go to '[...](https://localhost/?path=/story/pages-adt3dscenepage--mock-3-d-scene-page)'
2. Click on '+ Add New'
3. Fill Create new scene page 'Link 3D file in .glb format'
4. Click on Create button
5. See error

**Expected behavior**
It should upload the selected .glb file into the target storage container

**Screenshots**
It is attached
![image](https://user-images.githubusercontent.com/13743867/175258625-6451adb9-22ec-4d5a-b8d6-e8f9f99c50df.png)

**Browser (please complete the following information):**
 - Edge
 - Chrome

**Additional context**
I have not created app registration in AAD for the app, but have the Digital Twin Instance and Storage Account with proper roles

**Comment by BrennaCourtney** [comment]
fixed by https://github.com/microsoft/iot-cardboard-js/pull/641
