### ISSUE TITLE
Elements form doesn't allow selection of multiple meshes

### ISSUE THREAD

**Issue by pasanchMSFT** [microsoft/iot-cardboard-js#609]
**Describe the bug**
On Element creation several meshes could be selected to attach to the element. Currently only the first mesh selected is stored. Clicking around in the scene is possible but all meshes other than the first one are ignored.  

**To Reproduce**
1. Go to Scene page story
2. Navigate to element list
3. Click on 'Create element'
4. Try to select more than one mesh for the element
5. See how only the first one selected is stored.

**Expected behavior**
Element creation should support picking several meshes.

**Screenshots**
![bugElementCreation](https://user-images.githubusercontent.com/55852250/176779180-b686cf80-26f7-4b84-9ae5-e452b1a52589.gif)

**Browser (please complete the following information):**
Edge browser

**Comment by BrennaCourtney** [comment]
addressed by https://github.com/microsoft/iot-cardboard-js/pull/597
