### ISSUE TITLE
Twin list is not sorted when creating an element

### ISSUE THREAD

**Issue by msnyder-msft** [microsoft/iot-cardboard-js#654]
**Describe the bug**
The list of twins in the TwinId dropdown on ElementForm is not sorted so the items are randomly ordered.

**To Reproduce**
1. Go to a scene
2. Create a new element
3. Click the twin id dropdown

**Expected behavior**
The list of twins should be sorted alphabetically

**Screenshots**
![image](https://user-images.githubusercontent.com/57726991/181582450-25e3e105-d2ce-4f58-b6a4-ebe98a8dd2f0.png)

**Comment by abalogun-dev** [comment]
Addressed here: https://github.com/microsoft/iot-cardboard-js/pull/734
