### ISSUE TITLE
3DConfig file showing as a selectable 3D asset

### ISSUE THREAD

**Issue by ptallettms** [microsoft/iot-cardboard-js#677]
**Describe the bug**
When creating a new scene, the 3d config file is offered as a choice of 3D model in the dropdown

**To Reproduce**
1. Go to Mock3DScenePage story
2. Click on Add scene
3. Click on CHOOSE FILE dropdown
4. 3DConfig.json shown as a choice

**Expected behavior**
json file should not be shown in dropdown

**Screenshots**
![image](https://user-images.githubusercontent.com/85894309/184701146-96f3e771-7e82-4687-aa14-5f5b571383fd.png)

**Browser (please complete the following information):**
 - Browser [e.g. chrome, safari, edge] Edge

**Additional context**

**Comment by abalogun-dev** [comment]
Addressed here: https://github.com/microsoft/iot-cardboard-js/pull/735
