### ISSUE TITLE
Console warning

### ISSUE THREAD

**Issue by ptallettms** [microsoft/iot-cardboard-js#678]
**Describe the bug**
A compilation warning is shown in the console on startup

**To Reproduce**
1. npm run storybook
2. View console

**Expected behavior**
No warning

**Screenshots**
./src/Models/Context/index.ts 2:0-137"export 'IDeeplinkContextProviderProps' was not found in './DeeplinkContext/DeeplinkContext.types'./src/Models/Context/index.ts 2:0-137"export 'IPublicDeeplink' was not found in './DeeplinkContext/DeeplinkContext.types'./src/Models/Context/index.ts 6:0-94"export 'ISceneThemeContextProviderProps' was not found in './SceneThemeContext/SceneThemeContext.types'./src/Models/Context/index.ts 8:0-91"export 'ISceneViewContextProviderProps' was not found in './SceneViewContext/SceneViewContext.types'

**Browser (please complete the following information):**
 - Browser [e.g. chrome, safari, edge] Edge

**Additional context**

**Comment by msnyder-msft** [comment]
I'm confused because these exports DO exist....
![image](https://user-images.githubusercontent.com/57726991/184704125-8158f0ad-b492-4968-acc8-7525a9a5cb66.png)
![image](https://user-images.githubusercontent.com/57726991/184704150-a708df0f-078d-4d04-8d0a-de2deb43ffad.png)
