### ISSUE TITLE
AGPL3 violation

### ISSUE THREAD

**Issue by xeolabs** [microsoft/iot-cardboard-js#685]
Hi, I just spotted an AGPL3 violation (@xeokit/xeokit-sdk):
https://github.com/microsoft/iot-cardboard-js/blob/main/package.json#L48

Sounds like it was only used for prototyping, so shouldn't have an impact.

**Comment by darsney** [comment]
ahh yes correct, the xeokit work was from some early prototypes but can probably be removed as cruft, good call

**Comment by darsney** [comment]
Removed xeokit references
