### ISSUE TITLE
Possibility to use access token

### ISSUE THREAD

**Issue by n00bm5st3r69** [microsoft/iot-cardboard-js#762]
Is it possible to use access token instead of logging in via MSAL when using a component for example the ADT3DViewer component?

**Comment by darsney** [comment]
You could theoretically use a different AuthenticationService that has a getToken method that supplies a hardcoded token, although access tokens will generally expire within 24 hours or so, that is why it is important to use something like MSAL, which makes sure that stale tokens are refreshed whenever necessary.  So the short answer is yes, but probably don't
