### ISSUE TITLE
Status Update - Rena Liu

### ISSUE THREAD

**Issue by renaaliu** [microsoft/iot-cardboard-js#878]
3/6
- Human user feedback:
- UI change mockup w/Peyton & Konstantin
- bug bash procedure plans after offline benchmarks are measured
- privacy review in progress but not a blocker for gathering user feedback
----------------------------------
3/2
- 1P survey data analysis: who's onboarded, data file types, data storage types
- 1P customer onboarding instructions https://microsoft.sharepoint.com/:w:/t/CognitiveServiceLanguagePillar/EU-F2ujNFJJAuteBfJlbRukBORSgVUocuHodWT-zVuFXMg?e=fxjg0C most pertinent info will be added to wiki
- 1P office hours
- Human user feedback: UI change mockup w/Peyton & Konstantin, bug bash procedure plans after offline benchmarks are measured; privacy review in progress but not a blocker for gathering user feedback

Still in the backlog
- small wiki updates
- change log in the wiki
- ------------------------------------------------------------------
2/27
Done/Working on
- Customer onboarding guidelines https://microsoft.sharepoint.com/:w:/t/CognitiveServiceLanguagePillar/EU-F2ujNFJJAuteBfJlbRukBORSgVUocuHodWT-zVuFXMg?e=TwMhyb
- Human feedback process testing

Asks:
- Chunking & authoring experience updates at eGPT sycn
- Code sample for users
- Portal template code sample for users

To Do
- Check in with Privacy Champ
- Set up time to overview data inventory & flow
-----------------------------------------------
2/23
- Sync-ed with Partinita about privacy review, she recommends working with privacy champ, not available until next week though
       - Need data flow diagrams & data collection inventory completed in the meantime
- Working on release procedures doc  https://microsoft.sharepoint.com/:w:/t/CognitiveServiceLanguagePillar/EY70d9-1FKlJpEwrhCbdpn8Btsjs4uDXbW_6J-zxeMzQdw?e=mdyme4
- Customer human feedback procedure with Haiyuan
- Docs updates with Chelsea - FAQs & FYI for customers, release updates
- ----------------------------------------------------------------------
- Starting privacy review for data collection with Parinita
- Sharing data collection instructions with AKS team 5:30PST

Ask:
- Review AKS's data flow diagram: https://microsoftapc-my.sharepoint.com/:w:/g/personal/yudian_microsoft_com/EcEOcXIqMDBOq_wvjTc5Ok0Bgq_LQr49yWqiVbc6_O-86A?e=VUAF9K&nav=eyJoIjoiMTI3NjQ2NjI2MSJ9&CID=09EE682A-2A78-4B3A-90BF-070AD7AB2C50

-----------------------------------------------------------------------------------------------------
Blocked: Subscription access for TScience to create privacy feature review for data collection features

Next Steps:
- Working with AKS team & Peyton for human feedback to queries - updating UI, etc.
- Continuing syncs with Azure portal, AKS, and other 1P teams to start onboarding and feedback exchange at the private preview stage
- Working with Haiyuan, Himanshu and Atabak on non-chunked doc input plans

**Comment by darsney** [comment]
Umm, I feel like this is not in the right place.  @renaaliu what is this...for?

**Comment by montgomp** [comment]
Added `invalid` tag. @renaaliu can you verify this issue is in the right project?
